apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  annotations:
    kompose.cmd: kompose convert -f /tmp/workforce-compose.yaml -o k8s/
    kompose.version: 1.38.0 (HEAD)
  labels:
    io.kompose.service: postgres
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f /tmp/workforce-compose.yaml -o k8s/
        kompose.version: 1.38.0 (HEAD)
      labels:
        io.kompose.service: postgres
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: workforce
            - name: POSTGRES_PASSWORD
              value: workforce
            - name: POSTGRES_USER
              value: workforce
          image: postgres:16-alpine
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -U workforce
            failureThreshold: 10
            periodSeconds: 5
          name: postgres
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
      restartPolicy: Always
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data
